services:
  device1:
    build : ./device1
    container_name: device1
    networks:
      network1:
        ipv4_address: 192.168.100.2

  device2:
    build : ./device2
    container_name: device2
    networks:
      network1:
        ipv4_address: 192.168.100.3

networks:
  network1:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
          gateway: 192.168.100.1
